#!/usr/bin/env bash
# Transfers a file from a client to a server using scp

if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

file_path="$1"
ip="$2"
username="$3"
ssh_key="${4:-}"

scp_options="-o StrictHostKeyChecking=no"
if [ -n "$ssh_key" ]; then
    scp_options+=" -i $ssh_key"
fi

scp $scp_options "$file_path" "$username@$ip:~/"
