#!/usr/bin/env bash

# Update the package lists
sudo apt-get update

# Install nginx server
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create the HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# test nginx config
sudo nginx -t

# Start the nginx service
sudo service nginx reload

