#!/usr/bin/env bash
# Script to install and configure HAProxy Load balancer

# Check if running as root user
if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root or using sudo."
    exit 1
fi

# Check if HAProxy is not installed
if ! dpkg -s haproxy &> /dev/null; then
    # Install HAProxy
    apt-get update
    apt-get install -y haproxy
fi

CONFIG_FILE="/etc/haproxy/haproxy.cfg"
BACKUP_FILE="/etc/haproxy/haproxy.cfg.bak"

# Check if haproxy.cfg exists
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Configuration file $CONFIG_FILE does not exist. Skipping backup..."
else
    # Backup haproxy.cfg file if it doesn't already exist
    if [[ ! -f "$BACKUP_FILE" ]]; then
        cp "$CONFIG_FILE" "$BACKUP_FILE"
        echo "Backup created: $BACKUP_FILE"
    else
        echo "Backup already exists: $BACKUP_FILE"
    fi
fi

# Append configuration to haproxy.cfg
read -r -d '' PROXIES <<EOF
frontend aneke-frontend
    bind *:80
    default_backend 220812-web_servers
    option forwardfor

backend aneke-backend
    balance roundrobin
    server web-01 220812-web-01:80 check
    server web-02 220812-web-02:80 check

EOF

# Check if the configuration already exists in the file
if grep -q "frontend aneke-frontend" "$CONFIG_FILE" && grep -q "backend aneke-backend" "$CONFIG_FILE"; then
    echo "Configuration already exists in $CONFIG_FILE. Skipping..."
else
    # Append the PROXIES variable to the haproxy.cfg file
	{ echo; echo "$PROXIES"; } | sudo tee -a "$CONFIG_FILE" >/dev/null
    echo "Configuration appended to $CONFIG_FILE."
fi

# Restart HAProxy Load balancer
service haproxy restart
