#!/usr/bin/env bash
# Script to create an RSA key pair

# Set variables
key_name="school"
key_bits=4096
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f "$key_name" -N "$passphrase"

# Print success message
echo "RSA key pair created successfully."
echo "Private key saved as: $key_name"
echo "Public key saved as: $key_name.pub"

